
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/chrstein/data/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - network
    restart: on-failure

  wordpress:
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - /home/chrstein/data/wordpress:/var/www/html
    networks:
      - network
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    container_name: mariadb
    volumes:
      - /home/chrstein/data/wordpress:/var/www/html
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${WP_ADMIN_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

networks:
  network:
    driver: bridge
