
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    networks:
      - network
    restart: no

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: no

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - network
    restart: no

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/chrstein/data/wordpress
      o: bind
  mariadb_data:
     driver: local
     driver_opts:
      type: none
      device: /home/chrstein/data/mysql
      o: bind

networks:
  network:
    driver: bridge